import { Types } from 'mongoose';
import { HttpError } from '../middleware/error.js';
import {
  Assignment,
  AttendanceRecord,
  Course,
  Enrollment,
  Material,
  ModuleModel,
  SessionModel,
  type AssignmentDoc,
  type HydratedSession,
  type ModuleDoc,
  type SessionDoc,
  type SessionStatus,
} from '../models/index.js';
import type { AuthContext } from '../middleware/auth.js';
import { recordAudit } from './auditService.js';
import { assertFacultyCanWriteCourse, assertFacultyOwnsCourse } from './authzService.js';

// Phase B-2 session lifecycle.
//
// State machine (per developer-handoff §8):
//   upcoming → in_progress → completed
//                                ↓ (within 7d, by the marker or superadmin)
//                            in_progress
//
// Completion gate: at least one AttendanceRecord must exist for the
// session before it can transition to `completed`. This is the only
// non-trivial business rule in the machine and matches §8: "completion
// requires attendance to have been taken".
//
// Undo window: completedAt + 7 days. After that, the row is locked even
// for the original marker. Superadmin can still uncomplete because of
// oversight, but they can't bypass the 7-day rule — the spec is firm
// (§8: "after that it requires a super admin to reopen" — interpreted as
// requires a fresh re-completion, not a different lock semantic).

const UNDO_WINDOW_MS = 7 * 24 * 60 * 60 * 1000;

interface ActorCtx {
  ip?: string;
  ua?: string;
}

export interface SessionDto {
  id: string;
  moduleId: string;
  courseId: string;
  number: number;                  // exposed as orderIndex too for callers
  orderIndex: number;
  title: string;
  description: string;
  type: SessionDoc['type'];
  plannedMinutes: number | null;
  scheduledStart: string | null;
  scheduledEnd: string | null;
  location: string | null;
  status: SessionStatus;
  completedAt: string | null;
  completedBy: string | null;
  completionUndoableUntil: string | null;
  notes: string;                   // staff-facing only — never serialise to students
  sourceLessonId: string | null;
  linkedMLOs: string[];
  bloomLevel: string | null;
  objectives: string[];
  activities: SessionDoc['activities'];
  formativeChecks: SessionDoc['formativeChecks'];
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export function toSessionDto(doc: HydratedSession | SessionDoc): SessionDto {
  return {
    id: String(doc._id),
    moduleId: doc.moduleId.toString(),
    courseId: doc.courseId.toString(),
    number: doc.number,
    orderIndex: doc.number,
    title: doc.title,
    description: doc.description,
    type: doc.type,
    plannedMinutes: doc.plannedMinutes,
    scheduledStart: doc.scheduledStart ? doc.scheduledStart.toISOString() : null,
    scheduledEnd: doc.scheduledEnd ? doc.scheduledEnd.toISOString() : null,
    location: doc.location,
    status: doc.status,
    completedAt: doc.completedAt ? doc.completedAt.toISOString() : null,
    completedBy: doc.completedBy ? doc.completedBy.toString() : null,
    completionUndoableUntil: doc.completionUndoableUntil
      ? doc.completionUndoableUntil.toISOString()
      : null,
    notes: doc.notes ?? '',
    sourceLessonId: doc.sourceLessonId,
    linkedMLOs: doc.linkedMLOs,
    bloomLevel: doc.bloomLevel,
    objectives: doc.objectives,
    activities: doc.activities,
    formativeChecks: doc.formativeChecks,
    isAutoGenerated: Boolean(doc.synthesized),
    createdAt: doc.createdAt.toISOString(),
    updatedAt: doc.updatedAt.toISOString(),
  };
}

async function loadSessionForStaff(
  actor: AuthContext,
  sessionId: string,
): Promise<HydratedSession> {
  if (!Types.ObjectId.isValid(sessionId)) {
    throw new HttpError(404, 'NOT_FOUND', 'Session not found.');
  }
  const session = await SessionModel.findOne({ _id: sessionId, deletedAt: null });
  if (!session) throw new HttpError(404, 'NOT_FOUND', 'Session not found.');
  await assertFacultyOwnsCourse(actor.userId, actor.role, session.courseId);
  return session;
}

/**
 * M10o — Sessions in a batch on a specific IST date. Used by the
 * "click batch → attendance" flow on the Faculty Dashboard: we resolve
 * every course enrolled to this batch, then return today's sessions
 * across all those courses. Each session shows the course name so
 * faculty can pick the right one to mark attendance on.
 */
export interface BatchSessionSummary {
  id: string;
  courseId: string;
  courseName: string;
  moduleId: string;
  title: string;
  scheduledStart: string | null;
  scheduledEnd: string | null;
  status: 'planned' | 'completed' | 'cancelled' | 'unscheduled';
  attendanceRecorded: number;
  enrolledStudents: number;
}

export async function listSessionsForBatchOnDate(
  actor: AuthContext,
  batchIdStr: string,
  dateIsoYmd: string,
): Promise<BatchSessionSummary[]> {
  if (!Types.ObjectId.isValid(batchIdStr)) {
    throw new HttpError(404, 'NOT_FOUND', 'Batch not found.');
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateIsoYmd)) {
    throw new HttpError(422, 'VALIDATION_FAILED', 'date must be YYYY-MM-DD.');
  }
  const batchId = new Types.ObjectId(batchIdStr);

  // The day window is in UTC; close enough for IST-school scheduling
  // (covers IST 05:30 → next-day 05:30 which includes the entire school
  // day).
  const dayFrom = new Date(`${dateIsoYmd}T00:00:00.000Z`);
  const dayTo = new Date(`${dateIsoYmd}T23:59:59.999Z`);

  // Resolve every enrolment for this batch → course IDs the batch is on.
  const enrolments = await Enrollment.find({ batchId, status: { $ne: 'revoked' } })
    .select({ courseId: 1, studentId: 1 })
    .lean();
  const courseIds = [...new Set(enrolments.map((e) => String(e.courseId)))].map(
    (s) => new Types.ObjectId(s),
  );
  if (courseIds.length === 0) return [];

  // Faculty can only see sessions of courses they teach. For admin /
  // superadmin / admissions_officer we skip the filter.
  let effectiveCourseIds = courseIds;
  if (actor.role === 'faculty') {
    const myCourses = await Course.find({
      _id: { $in: courseIds },
      facultyIds: actor.userId,
      deletedAt: null,
    })
      .select({ _id: 1 })
      .lean();
    const allowed = new Set(myCourses.map((c) => String(c._id)));
    effectiveCourseIds = courseIds.filter((id) => allowed.has(id.toString()));
  }
  if (effectiveCourseIds.length === 0) return [];

  const courses = await Course.find({ _id: { $in: effectiveCourseIds } })
    .select({ name: 1 })
    .lean();
  const courseNameMap = new Map(
    courses.map((c) => [String(c._id), c.name as string]),
  );

  const sessions = await SessionModel.find({
    courseId: { $in: effectiveCourseIds },
    deletedAt: null,
    scheduledStart: { $gte: dayFrom, $lte: dayTo },
  })
    .sort({ scheduledStart: 1 })
    .lean();

  if (sessions.length === 0) return [];

  // Attendance roll-up per session in one aggregation.
  const sessionIds = sessions.map((s: { _id: Types.ObjectId }) => s._id);
  const studentIds = [...new Set(enrolments.map((e) => String(e.studentId)))].map(
    (s) => new Types.ObjectId(s),
  );
  const attendanceAgg = await AttendanceRecord.aggregate([
    { $match: { sessionId: { $in: sessionIds } } },
    { $group: { _id: '$sessionId', n: { $sum: 1 } } },
  ]);
  const attCountMap = new Map<string, number>(
    attendanceAgg.map((a: { _id: Types.ObjectId; n: number }) => [
      String(a._id),
      a.n,
    ]),
  );

  return sessions.map((s) => ({
    id: String(s._id),
    courseId: String(s.courseId),
    courseName: courseNameMap.get(String(s.courseId)) ?? '(deleted)',
    moduleId: String(s.moduleId),
    title: s.title as string,
    scheduledStart: s.scheduledStart
      ? (s.scheduledStart as Date).toISOString()
      : null,
    scheduledEnd: s.scheduledEnd ? (s.scheduledEnd as Date).toISOString() : null,
    status: (s.status ?? 'planned') as
      | 'planned'
      | 'completed'
      | 'cancelled'
      | 'unscheduled',
    attendanceRecorded: attCountMap.get(String(s._id)) ?? 0,
    enrolledStudents: studentIds.length,
  }));
}

/** List sessions for a course, ordered by module then number. */
export async function listSessionsForCourse(
  actor: AuthContext,
  courseId: string,
): Promise<SessionDto[]> {
  if (!Types.ObjectId.isValid(courseId)) {
    throw new HttpError(404, 'NOT_FOUND', 'Course not found.');
  }
  const course = await Course.findOne({ _id: courseId, deletedAt: null });
  if (!course) throw new HttpError(404, 'NOT_FOUND', 'Course not found.');
  await assertFacultyOwnsCourse(actor.userId, actor.role, course._id);

  const docs = await SessionModel.find({
    courseId: course._id,
    deletedAt: null,
  }).sort({ moduleId: 1, number: 1 });
  return docs.map(toSessionDto);
}

/** Session detail with related materials + assignments + attendance count. */
export interface SessionDetailDto {
  session: SessionDto;
  materials: Array<{
    id: string;
    type: string;
    title: string;
    url: string | null;
    sizeBytes: number | null;
    slideCount: number | null;
  }>;
  assignments: Array<{
    id: string;
    title: string;
    dueAt: string;
    maxScore: number;
    deliveryVariant: string | null;
  }>;
  attendanceSummary: {
    recorded: number;
    enrolled: number;
    present: number;
    absent: number;
    late: number;
    excused: number;
  };
}

export async function getSessionDetail(
  actor: AuthContext,
  sessionId: string,
): Promise<SessionDetailDto> {
  const session = await loadSessionForStaff(actor, sessionId);

  const [materials, assignments, attendanceCounts, enrolmentCount] = await Promise.all([
    Material.find({ sessionId: session._id, deletedAt: null }).sort({ createdAt: 1 }).lean(),
    Assignment.find({ sessionId: session._id, deletedAt: null }).sort({ dueAt: 1 }).lean(),
    AttendanceRecord.aggregate<{ _id: string; count: number }>([
      { $match: { sessionId: session._id } },
      { $group: { _id: '$status', count: { $sum: 1 } } },
    ]),
    countActiveEnrolments(session.courseId),
  ]);

  const counts = {
    recorded: 0,
    present: 0,
    absent: 0,
    late: 0,
    excused: 0,
  };
  for (const r of attendanceCounts) {
    counts.recorded += r.count;
    if (r._id === 'present') counts.present = r.count;
    if (r._id === 'absent') counts.absent = r.count;
    if (r._id === 'late') counts.late = r.count;
    if (r._id === 'excused') counts.excused = r.count;
  }

  return {
    session: toSessionDto(session),
    materials: materials.map((m) => ({
      id: String(m._id),
      type: m.type as string,
      title: m.title as string,
      url: (m.url as string | null) ?? null,
      sizeBytes: (m.sizeBytes as number | null) ?? null,
      slideCount: (m.slideCount as number | null) ?? null,
    })),
    assignments: assignments.map((a) => ({
      id: String(a._id),
      title: a.title as string,
      dueAt: (a.dueAt instanceof Date ? a.dueAt : new Date(a.dueAt as string)).toISOString(),
      maxScore: a.maxScore as number,
      deliveryVariant: (a.deliveryVariant as string | null) ?? null,
    })),
    attendanceSummary: { ...counts, enrolled: enrolmentCount },
  };
}

async function countActiveEnrolments(courseId: Types.ObjectId): Promise<number> {
  const { Enrollment } = await import('../models/index.js');
  return Enrollment.countDocuments({ courseId, status: 'active' });
}

export async function markSessionComplete(
  actor: AuthContext,
  sessionId: string,
  ctx: ActorCtx,
): Promise<HydratedSession> {
  const session = await loadSessionForStaff(actor, sessionId);
  await assertFacultyCanWriteCourse(actor.userId, actor.role, session.courseId);
  if (session.status === 'completed') {
    return session; // idempotent
  }

  // Gate: at least one AttendanceRecord must exist before completion.
  const attCount = await AttendanceRecord.countDocuments({ sessionId: session._id });
  if (attCount === 0) {
    throw new HttpError(
      409,
      'ATTENDANCE_REQUIRED',
      'Take attendance for at least one student before marking the session complete.',
    );
  }

  const before = session.toObject();
  const now = new Date();
  session.status = 'completed';
  session.completedAt = now;
  session.completedBy = actor.userId;
  session.completionUndoableUntil = new Date(now.getTime() + UNDO_WINDOW_MS);
  await session.save();

  await recordAudit({
    actorUserId: actor.userId,
    action: 'session.completed',
    targetType: 'Session',
    targetId: session._id,
    before,
    after: session.toObject(),
    details: {
      courseId: session.courseId.toString(),
      moduleId: session.moduleId.toString(),
      attendanceCount: attCount,
    },
    ip: ctx.ip,
    ua: ctx.ua,
  });
  return session;
}

export async function markSessionIncomplete(
  actor: AuthContext,
  sessionId: string,
  ctx: ActorCtx,
): Promise<HydratedSession> {
  const session = await loadSessionForStaff(actor, sessionId);
  await assertFacultyCanWriteCourse(actor.userId, actor.role, session.courseId);
  if (session.status !== 'completed') {
    throw new HttpError(
      409,
      'INVALID_TRANSITION',
      `Cannot uncomplete from status '${session.status}'.`,
    );
  }
  if (!session.completionUndoableUntil || new Date() > session.completionUndoableUntil) {
    throw new HttpError(
      409,
      'COMPLETION_LOCKED',
      'The 7-day undo window has expired. This session is locked.',
    );
  }
  // Only the marker (or superadmin) can undo.
  const isMarker = session.completedBy?.equals(actor.userId) ?? false;
  if (!isMarker && actor.role !== 'superadmin') {
    throw new HttpError(
      403,
      'FORBIDDEN',
      'Only the faculty who marked this session complete (or a super admin) may undo it.',
    );
  }

  const before = session.toObject();
  session.status = 'in_progress';
  session.completedAt = null;
  session.completedBy = null;
  session.completionUndoableUntil = null;
  await session.save();

  await recordAudit({
    actorUserId: actor.userId,
    action: 'session.uncompleted',
    targetType: 'Session',
    targetId: session._id,
    before,
    after: session.toObject(),
    details: {
      courseId: session.courseId.toString(),
      moduleId: session.moduleId.toString(),
    },
    ip: ctx.ip,
    ua: ctx.ua,
  });
  return session;
}

export interface UpdateSessionInput {
  title?: string;
  description?: string;
  type?: SessionDoc['type'];
  plannedMinutes?: number | null;
  scheduledStart?: string | null;
  scheduledEnd?: string | null;
  location?: string | null;
  notes?: string;
  // Reorder fields. orderIndex is the new position within the target module.
  // If moduleId moves, the session is renumbered into that module.
  moduleId?: string;
  orderIndex?: number;
}

export async function updateSession(
  actor: AuthContext,
  sessionId: string,
  input: UpdateSessionInput,
  ctx: ActorCtx,
): Promise<HydratedSession> {
  const session = await loadSessionForStaff(actor, sessionId);
  await assertFacultyCanWriteCourse(actor.userId, actor.role, session.courseId);
  const before = session.toObject();

  // Auto-generated sessions: title is read-only; reorder is blocked.
  const isAutoGen = Boolean(session.synthesized);
  if (isAutoGen && input.title !== undefined && input.title !== session.title) {
    throw new HttpError(
      409,
      'SESSION_AUTO_GENERATED',
      'The title of an auto-generated session cannot be changed.',
    );
  }
  const movingModule = input.moduleId !== undefined && input.moduleId !== session.moduleId.toString();
  const movingOrder = input.orderIndex !== undefined && input.orderIndex !== session.number;
  if (isAutoGen && (movingModule || movingOrder)) {
    throw new HttpError(
      409,
      'SESSION_AUTO_GENERATED',
      'Auto-generated sessions cannot be reordered or moved between modules.',
    );
  }

  // Validate target module if moving.
  let targetModule: ModuleDoc | null = null;
  if (movingModule) {
    if (!Types.ObjectId.isValid(input.moduleId!)) {
      throw new HttpError(422, 'VALIDATION_FAILED', 'moduleId is invalid.');
    }
    targetModule = await ModuleModel.findOne({ _id: input.moduleId, deletedAt: null });
    if (!targetModule) throw new HttpError(404, 'NOT_FOUND', 'Target module not found.');
    if (!targetModule.courseId.equals(session.courseId)) {
      throw new HttpError(
        409,
        'CROSS_COURSE_MOVE_FORBIDDEN',
        'A session cannot be moved to a module in a different course.',
      );
    }
  }

  // Plain edits.
  if (input.title !== undefined && !isAutoGen) session.title = input.title.trim();
  if (input.description !== undefined) session.description = input.description;
  if (input.type !== undefined) session.type = input.type;
  if (input.plannedMinutes !== undefined) session.plannedMinutes = input.plannedMinutes;
  if (input.scheduledStart !== undefined) {
    session.scheduledStart = input.scheduledStart ? new Date(input.scheduledStart) : null;
  }
  if (input.scheduledEnd !== undefined) {
    session.scheduledEnd = input.scheduledEnd ? new Date(input.scheduledEnd) : null;
  }
  if (input.location !== undefined) session.location = input.location;
  if (input.notes !== undefined) session.notes = input.notes;

  // Reorder.
  if (movingModule || movingOrder) {
    await reorderSession(session, targetModule?._id ?? session.moduleId, input.orderIndex ?? session.number);
  } else {
    await session.save();
  }

  await recordAudit({
    actorUserId: actor.userId,
    action: movingModule || movingOrder ? 'session.reordered' : 'session.updated',
    targetType: 'Session',
    targetId: session._id,
    before,
    after: session.toObject(),
    details: {
      courseId: session.courseId.toString(),
      moduleIdBefore: before.moduleId.toString(),
      moduleIdAfter: session.moduleId.toString(),
      numberBefore: before.number,
      numberAfter: session.number,
    },
    ip: ctx.ip,
    ua: ctx.ua,
  });

  return session;
}

/**
 * Renumber a single session into a target module + position. Sessions in
 * the source module shift down to fill the gap; sessions in the target
 * module shift up to make room. Done as a multi-write under no transaction
 * because the unique (moduleId, number) index would block in-place swaps.
 *
 * Strategy: park every affected session at a temporary high number first
 * (1e6 + offset), then re-assign final numbers — guarantees no unique-index
 * collision mid-flight.
 */
async function reorderSession(
  session: HydratedSession,
  newModuleId: Types.ObjectId,
  rawNewIndex: number,
): Promise<void> {
  const oldModuleId = session.moduleId;
  const sameModule = oldModuleId.equals(newModuleId);

  // Pull the affected sessions from both modules, alive only.
  const sourceSiblings = await SessionModel.find({
    moduleId: oldModuleId,
    deletedAt: null,
    _id: { $ne: session._id },
  }).sort({ number: 1 });
  const targetSiblings = sameModule
    ? sourceSiblings
    : await SessionModel.find({
      moduleId: newModuleId,
      deletedAt: null,
    }).sort({ number: 1 });

  // Park everything that might collide at a temporary high number range.
  const PARK_BASE = 1_000_000;
  const allAffected = sameModule
    ? [session, ...sourceSiblings]
    : [session, ...sourceSiblings, ...targetSiblings];
  const parkOps = allAffected.map((s, i) => ({
    updateOne: {
      filter: { _id: s._id },
      update: { $set: { number: PARK_BASE + i } },
    },
  }));
  if (parkOps.length > 0) {
    await SessionModel.bulkWrite(parkOps, { ordered: true });
  }

  // Compute final ordering.
  const clamp = (n: number, lo: number, hi: number): number => Math.max(lo, Math.min(hi, n));
  const newIndex = clamp(rawNewIndex, 0, targetSiblings.length);

  if (sameModule) {
    // Within-module move: rebuild order excluding this session, then insert it.
    const ordered = sourceSiblings.slice();
    ordered.splice(newIndex, 0, session);
    const finalOps = ordered.map((s, i) => ({
      updateOne: {
        filter: { _id: s._id },
        update: { $set: { moduleId: newModuleId, number: i } },
      },
    }));
    await SessionModel.bulkWrite(finalOps, { ordered: true });
  } else {
    // Cross-module move within a single course.
    const sourceFinal = sourceSiblings.map((s, i) => ({
      updateOne: {
        filter: { _id: s._id },
        update: { $set: { number: i } },
      },
    }));
    const targetOrdered = [
      ...targetSiblings.slice(0, newIndex),
      session,
      ...targetSiblings.slice(newIndex),
    ];
    const targetFinal = targetOrdered.map((s, i) => ({
      updateOne: {
        filter: { _id: s._id },
        update: { $set: { moduleId: newModuleId, number: i } },
      },
    }));
    await SessionModel.bulkWrite([...sourceFinal, ...targetFinal], { ordered: true });
  }

  // Re-hydrate in caller — refresh the doc.
  const fresh = await SessionModel.findById(session._id);
  if (fresh) {
    session.moduleId = fresh.moduleId;
    session.number = fresh.number;
  }
}

// Used by the route layer to expose a faculty-friendly DTO with author
// rollups, but the lookup itself stays in the service for testing.
export async function findCourseAssignmentForSession(sessionId: Types.ObjectId): Promise<AssignmentDoc | null> {
  return Assignment.findOne({ sessionId, deletedAt: null }).lean();
}

const PARK_BASE = 1_000_000;

/**
 * Boot-time recovery for the reorder parking-number strategy.
 *
 * `reorderSession` parks every affected session at numbers `>= 1_000_000`
 * before re-flushing them to their final positions. If the process dies
 * between parking and re-flushing — server crash, OOM kill, deploy
 * mid-request — those sessions are left with absurd order numbers. They
 * still appear in the UI (no number filter on list queries) but at the
 * bottom of their module, which is bad UX and confuses faculty.
 *
 * Strategy: scan for orphans on every API boot. Group by moduleId and
 * compact each module's session numbers, preserving the relative order
 * (parked > final-numbered would be append; final-numbered > parked is
 * impossible since parked numbers are always higher). Audit-log each
 * recovery so the operator can see the gap was repaired.
 *
 * Idempotent: safe to run on every boot. No-op when there are no orphans.
 */
export async function recoverStrandedSessions(): Promise<{
  modulesScanned: number;
  sessionsRecovered: number;
}> {
  // Cheap early exit. Index on { moduleId, number } makes the count fast.
  const orphanCount = await SessionModel.countDocuments({
    number: { $gte: PARK_BASE },
    deletedAt: null,
  });
  if (orphanCount === 0) return { modulesScanned: 0, sessionsRecovered: 0 };

  const orphans = await SessionModel.find({
    number: { $gte: PARK_BASE },
    deletedAt: null,
  }).select('_id moduleId').lean();

  const affectedModuleIds = Array.from(
    new Set(orphans.map((o) => o.moduleId.toString())),
  );

  let recovered = 0;
  for (const moduleIdStr of affectedModuleIds) {
    const moduleId = new Types.ObjectId(moduleIdStr);
    // Pull every session in this module (parked + normal) and re-number
    // by current position. Sessions with parked numbers sort to the end,
    // so they take the final slots — preserves the intent that they were
    // mid-flight to a target position we no longer know.
const sessions = await SessionModel.find({
      moduleId,
      deletedAt: null,
    }).sort({ number: 1 });
    const ops = sessions.map((s, i) => ({
      updateOne: {
        filter: { _id: s._id },
        update: { $set: { number: i } },
      },
    }));
    if (ops.length > 0) {
    await SessionModel.bulkWrite(ops, { ordered: true });
    }
    recovered += sessions.filter((s) => s.number >= PARK_BASE).length;

    // Audit-log the recovery so the operator has a record. Per-module row
    // — keeps the audit volume sane even on a wide blast radius.
await recordAudit({
      actorUserId: null,
      action: 'session.reordered',
      targetType: 'Module',
      targetId: moduleId,
      details: {
        recovery: true,
        orphansInModule: sessions.filter((s) => s.number >= PARK_BASE).length,
        totalSessionsInModule: sessions.length,
      },
    });
  }

  return { modulesScanned: affectedModuleIds.length, sessionsRecovered: recovered };
}
