import { Workbox } from 'workbox-window';

/**
 * Registers the Workbox service worker generated by vite-plugin-pwa.
 * No-op outside the browser or in dev mode. When `VITE_ENABLE_PWA=false`
 * we actively UNREGISTER any existing SW + clear its caches — this rescues
 * users who picked up an earlier deploy that did register a SW, so a hard
 * refresh is enough to get them back to a live-network app.
 *
 * On a new SW activating in the background, dispatches a `sw:update-ready`
 * window event so the UI (a banner / toast) can prompt the user to refresh.
 */
export function registerServiceWorker(): void {
  if (typeof window === 'undefined') return;
  if (!('serviceWorker' in navigator)) return;
  if (import.meta.env.DEV) return;

  if (import.meta.env.VITE_ENABLE_PWA === 'false') {
    // Clean up any SW + caches a previous deploy installed. Runs once per
    // page load; safe if nothing is registered (becomes a no-op).
    (async () => {
      try {
        const regs = await navigator.serviceWorker.getRegistrations();
        await Promise.all(regs.map((r) => r.unregister()));
        if ('caches' in window) {
          const keys = await caches.keys();
          await Promise.all(keys.map((k) => caches.delete(k)));
        }
      } catch {
        // best-effort; ignore
      }
    })().catch(() => {});
    return;
  }

  const wb = new Workbox('/sw.js');

  wb.addEventListener('waiting', () => {
    window.dispatchEvent(new CustomEvent('sw:update-ready'));
  });

  wb.register().catch((err: unknown) => {
    // Don't throw — SW failure must never block the app.
    console.warn('[sw] registration failed', err);
  });
}
