import { Workbox } from 'workbox-window';

/**
 * Registers the Workbox service worker generated by vite-plugin-pwa.
 * No-op outside the browser, in dev mode, or when the user opted out via
 * `VITE_ENABLE_PWA=false`.
 *
 * On a new SW activating in the background, dispatches a `sw:update-ready`
 * window event so the UI (a banner / toast) can prompt the user to refresh.
 */
export function registerServiceWorker(): void {
  if (typeof window === 'undefined') return;
  if (!('serviceWorker' in navigator)) return;
  if (import.meta.env.DEV) return;
  if (import.meta.env.VITE_ENABLE_PWA === 'false') return;

  const wb = new Workbox('/sw.js');

  wb.addEventListener('waiting', () => {
    window.dispatchEvent(new CustomEvent('sw:update-ready'));
  });

  wb.register().catch((err: unknown) => {
    // Don't throw — SW failure must never block the app.
    console.warn('[sw] registration failed', err);
  });
}
