import { Router, type NextFunction, type Request, type Response } from 'express';
import { Types } from 'mongoose';
import { requireAuth } from '../middleware/auth.js';
import { requireRole } from '../middleware/requireRole.js';
import { HttpError } from '../middleware/error.js';
import {
  Assignment,
  AssignmentSubmission,
  SessionModel,
  type HydratedAssignment,
  type HydratedSession,
} from '../models/index.js';
import {
  listEnrollmentsForStudent,
  toEnrollmentDto,
} from '../services/enrollmentService.js';
import { findCourseById, toCourseDto } from '../services/courseService.js';
import { listModulesForCourse, toModuleDto } from '../services/moduleService.js';
import { assertStudentCanAccessCourse } from '../services/moduleAccessService.js';
import { toStudentSubmissionDto } from '../services/assignmentSubmissionService.js';

// Student-safe DTOs. These deliberately omit faculty-only fields:
//   - Session.notes (private faculty notes)
//   - Session.completedBy (the faculty member's id is irrelevant to students)
//   - Session.linkedMLOs / activities / formativeChecks (lesson-plan internals)
//
// Anything we expose here lands in the student's browser. Be conservative.
interface StudentSessionDto {
  id: string;
  moduleId: string;
  courseId: string;
  number: number;
  orderIndex: number;
  title: string;
  description: string;
  type: HydratedSession['type'];
  plannedMinutes: number | null;
  scheduledStart: string | null;
  scheduledEnd: string | null;
  location: string | null;
  status: HydratedSession['status'];
  completedAt: string | null;
  isAutoGenerated: boolean;
}

function toStudentSessionDto(doc: HydratedSession): StudentSessionDto {
  return {
    id: String(doc._id),
    moduleId: doc.moduleId.toString(),
    courseId: doc.courseId.toString(),
    number: doc.number,
    orderIndex: doc.number,
    title: doc.title,
    description: doc.description,
    type: doc.type,
    plannedMinutes: doc.plannedMinutes,
    scheduledStart: doc.scheduledStart ? doc.scheduledStart.toISOString() : null,
    scheduledEnd: doc.scheduledEnd ? doc.scheduledEnd.toISOString() : null,
    location: doc.location,
    status: doc.status,
    completedAt: doc.completedAt ? doc.completedAt.toISOString() : null,
    isAutoGenerated: Boolean(doc.synthesized),
  };
}

function toAssignmentDto(doc: HydratedAssignment) {
  return {
    id: doc._id.toString(),
    courseId: doc.courseId.toString(),
    moduleId: doc.moduleId ? doc.moduleId.toString() : null,
    authorUserId: doc.authorUserId.toString(),
    title: doc.title,
    instructions: doc.instructions,
    dueAt: doc.dueAt.toISOString(),
    maxScore: doc.maxScore,
    state: doc.state,
    createdAt: doc.createdAt.toISOString(),
    updatedAt: doc.updatedAt.toISOString(),
  };
}

export function meCoursesRouter(): Router {
  const router = Router();
  router.use(requireAuth);
  router.use(requireRole('student'));

  // Alias of /v1/enrollments/me per D-031.
  router.get(
    '/',
    async (req: Request, res: Response, next: NextFunction) => {
      try {
        const docs = await listEnrollmentsForStudent(req.auth!.userId);
        res.status(200).json({ data: { enrolments: docs.map(toEnrollmentDto) } });
      } catch (err) {
        next(err);
      }
    },
  );

  // Course shell payload for the student-facing course page. Returns the
  // course header, the active enrolment, the legacy `modules` (M3 Module
  // collection — preserved for the student dashboard until Phase C
  // converges student + staff views), the Phase B-2 `sessions` (flat list
  // ordered by module → number), and the per-assignment submission state.
  // 404 for a missing or unpublished course; 403 for inactive enrolment,
  // expired validity, or fees suspension. The frontend keys off the
  // ApiHttpError code/status to render an empty state instead of crashing.
  router.get(
    '/:courseId',
    async (req: Request, res: Response, next: NextFunction) => {
      try {
        const { courseId } = req.params;
        if (!courseId || !Types.ObjectId.isValid(courseId)) {
          throw new HttpError(404, 'NOT_FOUND', 'Course not found.');
        }
        const course = await findCourseById(courseId);
        if (!course) {
          throw new HttpError(404, 'NOT_FOUND', 'Course not found.');
        }
        // Full student-access gate — rejects sandbox, non-enrolled, expired, and
        // fee-suspended students before any module URLs are exposed.
        const { enrolment } = await assertStudentCanAccessCourse(
          req.auth!.user,
          course,
        );
        const [modules, sessionDocs, assignmentDocs] = await Promise.all([
          listModulesForCourse(course._id.toString()),
          SessionModel.find({ courseId: course._id, deletedAt: null }).sort({
            moduleId: 1,
            number: 1,
          }),
          Assignment.find({ courseId: course._id, deletedAt: null })
            .sort({ dueAt: 1 })
            .limit(200),
        ]);
        const mySubs = await AssignmentSubmission.find({
          assignmentId: { $in: assignmentDocs.map((a) => a._id) },
          studentId: req.auth!.userId,
        });
        const subsByAssignment = new Map(
          mySubs.map((s) => [s.assignmentId.toString(), s]),
        );

        res.status(200).json({
          data: {
            course: toCourseDto(course),
            enrolment: toEnrollmentDto(enrolment),
            modules: modules.map(toModuleDto),
            sessions: sessionDocs.map(toStudentSessionDto),
            assignments: assignmentDocs.map((a) => ({
              ...toAssignmentDto(a),
              mySubmission: subsByAssignment.get(a._id.toString())
                ? toStudentSubmissionDto(subsByAssignment.get(a._id.toString())!)
                : null,
            })),
          },
        });
      } catch (err) {
        next(err);
      }
    },
  );

  return router;
}
