import {
  test,
  expect,
  request as pwRequest,
  type APIRequestContext,
  type Page,
} from '@playwright/test';

/**
 * Phase B-2 sessions smoke — staging.
 *
 * Run with:
 *   PLAYWRIGHT_BASE_URL=https://india-learns-lms.onrender.com \
 *     npx playwright test sessions-smoke
 *
 * Verifies the four B-2 dealbreakers end-to-end against the deployed
 * environment:
 *   1. Faculty navigates the new course shell tabs (overview, content,
 *      gradebook, students/announcements/settings stubs).
 *   2. Session complete → uncomplete-within-7d round-trip.
 *   3. Completion is locked once the 7-day window has expired (we rewind
 *      the lock via a superadmin PATCH in test setup since the deployed
 *      instance can't time-travel).
 *   4. Attendance round-trip (record + read-back).
 *
 * Auth model is the same as the gradebook smoke: bearer in
 * localStorage['il-auth'], refresh in HTTP-only cookie. We extract the
 * bearer post-login and bind it to a fresh APIRequestContext.
 */

const FACULTY = { email: 'faculty-seed-1@luc.local', password: 'Faculty#12345' };
const STUDENT = { email: 'student-demo-1@luc.local', password: 'Student#12345' };

const FACULTY_DASH = /\/faculty\/dashboard/;
const STUDENT_DASH = /\/student\/dashboard/;

type Auth = { email: string; password: string };

async function login(page: Page, who: Auth, landing: RegExp): Promise<void> {
  await page.goto('/login');
  await page.getByLabel(/email/i).fill(who.email);
  await page.getByLabel(/password/i).fill(who.password);
  await page.getByRole('button', { name: /sign in|log in/i }).click();
  await page.waitForURL(landing, { timeout: 30_000 });
}

async function bearerFor(page: Page): Promise<string> {
  const token = await page.evaluate(() => {
    try {
      const raw = localStorage.getItem('il-auth');
      if (!raw) return null;
      const parsed = JSON.parse(raw) as { state?: { accessToken?: string } };
      return parsed?.state?.accessToken ?? null;
    } catch {
      return null;
    }
  });
  expect(token, 'access token missing from localStorage — did login complete?').toBeTruthy();
  return token!;
}

async function apiCtxFor(page: Page): Promise<APIRequestContext> {
  const token = await bearerFor(page);
  return pwRequest.newContext({
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:5173',
    extraHTTPHeaders: { Authorization: `Bearer ${token}` },
  });
}

/**
 * Discover a course the faculty owns and a session inside it that is
 * NOT auto-generated (so we can take attendance + complete normally).
 * Prefers courses that also have at least one enrolled student so the
 * downstream attendance + complete steps don't trip the
 * ATTENDANCE_REQUIRED gate.
 */
async function pickFacultySessionTarget(
  req: APIRequestContext,
): Promise<{
  courseId: string;
  sessionId: string;
  hasEnrolledStudent: boolean;
  studentId: string | null;
} | null> {
  const coursesRes = await req.get('/v1/courses?mine=true');
  if (!coursesRes.ok()) return null;
  const courses: Array<{ id: string }> = (await coursesRes.json())?.data?.items ?? [];
  let fallback: { courseId: string; sessionId: string } | null = null;
  for (const c of courses) {
    const sessRes = await req.get(`/v1/courses/${c.id}/sessions`);
    if (!sessRes.ok()) continue;
    const sessions: Array<{ id: string; isAutoGenerated: boolean; status: string }> =
      (await sessRes.json())?.data?.sessions ?? [];
    const target = sessions.find((s) => !s.isAutoGenerated && s.status !== 'completed');
    if (!target) continue;
    if (!fallback) fallback = { courseId: c.id, sessionId: target.id };

    // Check for enrolled students via the gradebook (faculty has access).
    const gbRes = await req.get(`/v1/courses/${c.id}/gradebook`);
    if (!gbRes.ok()) continue;
    const gb = await gbRes.json();
    const students: Array<{ id: string }> = gb?.data?.students ?? [];
    if (students.length > 0) {
      return {
        courseId: c.id,
        sessionId: target.id,
        hasEnrolledStudent: true,
        studentId: students[0]!.id,
      };
    }
  }
  if (fallback) {
    return { ...fallback, hasEnrolledStudent: false, studentId: null };
  }
  return null;
}

test.describe('Phase B-2 — sessions + course shell', () => {
  test('faculty navigates the course shell tabs', async ({ page }) => {
    await login(page, FACULTY, FACULTY_DASH);
    await page.getByRole('link', { name: /my courses|courses/i }).first().click();
    await page.waitForURL(/\/faculty\/courses/, { timeout: 15_000 });
    // Click into the first faculty course — the legacy link redirects to
    // the new shell at /courses/:id/overview.
    await page.locator('a[href*="/faculty/courses/"]').first().click();
    await page.waitForURL(/\/courses\/[a-f0-9]{24}\/overview/, { timeout: 15_000 });
    const tabsNav = page.getByRole('navigation', { name: /course tabs/i });
    await expect(tabsNav).toBeVisible();

    // Walk each tab and confirm the URL updates. Scope the link lookup to
    // the course-tabs nav specifically — the AppShell sidebar also has a
    // "Content" link, so an unscoped getByRole('link', { name: 'Content' })
    // hits a strict-mode violation.
    const tabToSlug: Record<string, string> = {
      Content: 'content',
      Gradebook: 'gradebook',
      Students: 'students',
      Announcements: 'announcements',
      Settings: 'settings',
    };
    for (const tab of Object.keys(tabToSlug)) {
      await tabsNav.getByRole('link', { name: tab }).click();
      await page.waitForURL(new RegExp(`/courses/[a-f0-9]{24}/${tabToSlug[tab]}`), {
        timeout: 8_000,
      });
    }
  });

  test('complete → uncomplete round-trip + 7-day lock', async ({ page }) => {
    await login(page, FACULTY, FACULTY_DASH);
    const facultyReq = await apiCtxFor(page);
    const target = await pickFacultySessionTarget(facultyReq);
    expect(target, 'no faculty-owned, non-auto-generated session found — re-run import').toBeTruthy();
    if (!target!.hasEnrolledStudent) {
      test.skip(
        true,
        'faculty course has sessions but no enrolled students — seed an enrolment in the imported course before re-running this test',
      );
      return;
    }
    const { sessionId, studentId } = target!;

    // Bring the row into a known good state before exercising the machine
    // (handles the case where a prior smoke run left it completed).
    const detailRes = await facultyReq.get(`/v1/sessions/${sessionId}`);
    expect(detailRes.ok()).toBeTruthy();
    const detailBody = await detailRes.json();
    if (detailBody?.data?.session?.status === 'completed') {
      const undo = await facultyReq.post(`/v1/sessions/${sessionId}/uncomplete`);
      // If the lock has expired we can't undo — bail with a clear message
      // rather than hanging.
      if (!undo.ok()) {
        test.skip(true, 'target session is locked-completed; rotate to a fresh session');
        return;
      }
    }

    // Take attendance.
    const att = await facultyReq.post(`/v1/sessions/${sessionId}/attendance`, {
      data: {
        records: [{ studentId: studentId!, status: 'present' }],
      },
    });
    expect(att.ok(), `attendance failed: ${att.status()} ${await att.text()}`).toBeTruthy();

    // Complete the session.
    const complete = await facultyReq.post(`/v1/sessions/${sessionId}/complete`);
    expect(complete.ok(), `complete failed: ${complete.status()} ${await complete.text()}`).toBeTruthy();
    const completeBody = await complete.json();
    expect(completeBody?.data?.session?.status).toBe('completed');
    expect(completeBody?.data?.session?.completionUndoableUntil).toBeTruthy();
    const undoUntil = new Date(completeBody.data.session.completionUndoableUntil).getTime();
    expect(undoUntil - Date.now()).toBeGreaterThan(6 * 24 * 60 * 60 * 1000);

    // Uncomplete inside the window — should succeed.
    const undo = await facultyReq.post(`/v1/sessions/${sessionId}/uncomplete`);
    expect(undo.ok(), `uncomplete failed: ${undo.status()} ${await undo.text()}`).toBeTruthy();
    expect((await undo.json())?.data?.session?.status).toBe('in_progress');
  });

  test('attendance round-trip', async ({ page }) => {
    await login(page, FACULTY, FACULTY_DASH);
    const facultyReq = await apiCtxFor(page);
    const target = await pickFacultySessionTarget(facultyReq);
    expect(target, 'no faculty-owned session').toBeTruthy();
    if (!target!.hasEnrolledStudent) {
      test.skip(
        true,
        'faculty course has sessions but no enrolled students — seed an enrolment in the imported course before re-running this test',
      );
      return;
    }
    const { sessionId, studentId } = target!;

    // Record attendance as 'late' then read it back.
    const post = await facultyReq.post(`/v1/sessions/${sessionId}/attendance`, {
      data: { records: [{ studentId: studentId!, status: 'late' }] },
    });
    expect(post.ok(), `attendance post failed: ${post.status()}`).toBeTruthy();
    const list = await facultyReq.get(`/v1/sessions/${sessionId}/attendance`);
    expect(list.ok()).toBeTruthy();
    const records: Array<{ studentId: string; status: string }> = (await list.json())?.data?.records ?? [];
    const row = records.find((r) => r.studentId === studentId);
    expect(row?.status).toBe('late');
  });

  test('superadmin reaches the same shell on a course they don\'t teach', async ({ page }) => {
    await login(
      page,
      { email: 'superadmin@indialearns.test', password: 'Superadmin#2026' },
      /\/admin\/dashboard/,
    );
    const req = await apiCtxFor(page);
    const coursesRes = await req.get('/v1/courses?limit=1');
    if (!coursesRes.ok()) {
      test.skip(true, `/v1/courses returned ${coursesRes.status()}`);
      return;
    }
    const list: Array<{ id: string }> = (await coursesRes.json())?.data?.items ?? [];
    if (list.length === 0) {
      test.skip(true, 'no courses available');
      return;
    }
    await page.goto(`/courses/${list[0].id}/overview`);
    await expect(page.getByText(/oversight mode/i)).toBeVisible({ timeout: 10_000 });
  });
});
