import { useEffect, useMemo, useState, type JSX } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  DndContext,
  PointerSensor,
  useSensor,
  useSensors,
  closestCenter,
  type DragEndEvent,
} from '@dnd-kit/core';
import {
  SortableContext,
  arrayMove,
  useSortable,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import type { ModuleDto, GlossaryEntryDto, ReadingItemDto } from 'india-learns-shared-types';
import { Card } from '../../../components/ui/Card.js';
import { Badge } from '../../../components/ui/Badge.js';
import { Button } from '../../../components/ui/Button.js';
import { Input, TextArea } from '../../../components/ui/Input.js';
import { FileDropZone } from '../../../components/ui/FileDropZone.js';
import { GlossaryEditor, ReadingListEditor } from '../../../components/GlossaryReadingEditors.js';
import { FileLink } from '../../../components/FileLink.js';
import { ErrorAlert, EmptyState, Skeleton } from '../../../components/ui/States.js';
import {
  coursesApi,
  filesApi,
  modulesApi,
  sessionsApi,
  type SessionDto,
} from '../../../lib/endpoints.js';
import { ApiHttpError } from '../../../lib/api.js';
import { useCourseOversight } from '../../../contexts/CourseOversightContext.js';

/**
 * Content tab — Module → Session tree with @dnd-kit reordering.
 *
 * Drag rules (per developer-handoff §7 + B-2 spec):
 *   - Sessions can be reordered within a module.
 *   - Sessions can be moved to a different module in the same course
 *     (drop the dragged item onto a session in the target module).
 *   - Auto-generated sessions (synthesized: true) cannot be dragged.
 *   - Modules themselves are NOT reorderable (Phase A import order is
 *     authoritative until B-3).
 *
 * Optimistic UI: the local list updates instantly on drop; the PATCH call
 * persists the new (moduleId, orderIndex). On 4xx, we rollback to the
 * server state and surface the error inline.
 */
export function CourseContentTab({ courseId }: { courseId: string }): JSX.Element {
  const qc = useQueryClient();

  const courseQ = useQuery({
    queryKey: ['course', courseId, 'shell'],
    queryFn: () => coursesApi.get(courseId),
  });
  const sessionsQ = useQuery({
    queryKey: ['course', courseId, 'sessions'],
    queryFn: () => sessionsApi.listForCourse(courseId),
  });

  // Local copy for optimistic moves.
  const [optimistic, setOptimistic] = useState<SessionDto[] | null>(null);
  const [moveError, setMoveError] = useState<string | null>(null);
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());

  const sessions = useMemo<SessionDto[]>(
    () => optimistic ?? sessionsQ.data ?? [],
    [optimistic, sessionsQ.data],
  );

  const moveMut = useMutation({
    mutationFn: ({ id, moduleId, orderIndex }: { id: string; moduleId: string; orderIndex: number }) =>
      sessionsApi.update(id, { moduleId, orderIndex }),
    onSuccess: () => {
      setOptimistic(null);
      setMoveError(null);
      qc.invalidateQueries({ queryKey: ['course', courseId, 'sessions'] });
    },
    onError: (err) => {
      setOptimistic(null);
      const msg = err instanceof ApiHttpError ? err.message : 'Move failed; reverted.';
      setMoveError(msg);
    },
  });

  const grouped = useMemo(() => {
    const byModule = new Map<string, SessionDto[]>();
    for (const s of sessions) {
      if (!byModule.has(s.moduleId)) byModule.set(s.moduleId, []);
      byModule.get(s.moduleId)!.push(s);
    }
    for (const list of byModule.values()) list.sort((a, b) => a.orderIndex - b.orderIndex);
    return byModule;
  }, [sessions]);

  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));

  const sessionById = useMemo(() => {
    const m = new Map<string, SessionDto>();
    for (const s of sessions) m.set(s.id, s);
    return m;
  }, [sessions]);

  function handleDragEnd(event: DragEndEvent): void {
    const { active, over } = event;
    if (!over || active.id === over.id) return;
    const dragged = sessionById.get(String(active.id));
    const target = sessionById.get(String(over.id));
    if (!dragged || !target) return;
    if (dragged.isAutoGenerated) {
      setMoveError('Auto-generated sessions cannot be reordered.');
      return;
    }

    const sourceModuleId = dragged.moduleId;
    const targetModuleId = target.moduleId;

    if (sourceModuleId === targetModuleId) {
      // Within-module reorder — use arrayMove for the local optimistic update.
      const list = grouped.get(sourceModuleId) ?? [];
      const fromIdx = list.findIndex((s) => s.id === dragged.id);
      const toIdx = list.findIndex((s) => s.id === target.id);
      if (fromIdx === -1 || toIdx === -1) return;
      const reordered = arrayMove(list, fromIdx, toIdx);
      const next = sessions.map((s) => {
        if (s.moduleId !== sourceModuleId) return s;
        const newPos = reordered.findIndex((r) => r.id === s.id);
        return { ...s, orderIndex: newPos };
      });
      setOptimistic(next);
      moveMut.mutate({ id: dragged.id, moduleId: targetModuleId, orderIndex: toIdx });
    } else {
      // Cross-module move — drop above the target.
      const targetList = grouped.get(targetModuleId) ?? [];
      const targetIdx = targetList.findIndex((s) => s.id === target.id);
      const insertAt = targetIdx === -1 ? targetList.length : targetIdx;
      const sourceList = (grouped.get(sourceModuleId) ?? []).filter((s) => s.id !== dragged.id);
      const targetReordered = [
        ...targetList.slice(0, insertAt),
        { ...dragged, moduleId: targetModuleId },
        ...targetList.slice(insertAt),
      ];
      const next = sessions
        .filter((s) => s.id !== dragged.id)
        .map((s) => {
          if (s.moduleId === sourceModuleId) {
            const newPos = sourceList.findIndex((r) => r.id === s.id);
            return { ...s, orderIndex: newPos };
          }
          if (s.moduleId === targetModuleId) {
            const newPos = targetReordered.findIndex((r) => r.id === s.id);
            return { ...s, orderIndex: newPos };
          }
          return s;
        })
        .concat(targetReordered.filter((r) => r.id === dragged.id).map((r, i) => ({
          ...r,
          orderIndex: insertAt + i,
        })));
      setOptimistic(next);
      moveMut.mutate({ id: dragged.id, moduleId: targetModuleId, orderIndex: insertAt });
    }
  }

  if (courseQ.isLoading || sessionsQ.isLoading) return <Skeleton variant="card" />;
  if (courseQ.isError) return <ErrorAlert message={(courseQ.error as Error).message} />;
  if (sessionsQ.isError) return <ErrorAlert message={(sessionsQ.error as Error).message} />;

  const modules = courseQ.data?.modules ?? [];

  if (modules.length === 0) {
    return (
      <Card accent="orange">
        <EmptyState
          title="No content yet"
          message="Run the curriculum import or add modules manually to start building this course."
        />
      </Card>
    );
  }

  const allSessionIds = sessions.map((s) => s.id);

  return (
    <div className="space-y-3">
      {moveError && (
        <ErrorAlert message={moveError} />
      )}
      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
        <SortableContext items={allSessionIds} strategy={verticalListSortingStrategy}>
          <ul className="space-y-3">
            {modules.map((m, idx) => {
              const list = grouped.get(m.id) ?? [];
              const completed = list.filter((s) => s.status === 'completed').length;
              const isCollapsed = collapsed.has(m.id);
              return (
                <li key={m.id} className="rounded-2xl border border-black/5 bg-white">
                  <button
                    type="button"
                    onClick={() => {
                      setCollapsed((prev) => {
                        const next = new Set(prev);
                        if (next.has(m.id)) next.delete(m.id);
                        else next.add(m.id);
                        return next;
                      });
                    }}
                    className="w-full flex items-center justify-between gap-3 px-5 py-3 text-left hover:bg-surface-muted/50 rounded-t-2xl"
                    aria-expanded={!isCollapsed}
                  >
                    <div className="min-w-0 flex items-center gap-3">
                      <span className="text-xs uppercase tracking-wider text-muted font-bold whitespace-nowrap">
                        Module {idx + 1}
                      </span>
                      <span className="font-semibold text-brand-navy truncate">{m.title}</span>
                      <span className="text-xs text-muted">
                        {completed}/{list.length} sessions complete
                      </span>
                    </div>
                    <span aria-hidden className="text-muted text-lg select-none">
                      {isCollapsed ? '▸' : '▾'}
                    </span>
                  </button>
                  <ModuleRowActions module={m} courseId={courseId} lessonCount={list.length} />
                  {!isCollapsed && (
                    <div className="border-t border-black/5">
                      <ModuleOverviewPanel module={m} />
                      {list.length === 0 ? (
                        <p className="px-5 py-4 text-sm text-muted italic">No sessions in this module.</p>
                      ) : (
                        <ul className="divide-y divide-black/5">
                          {list.map((s) => (
                            <SortableSessionRow
                              key={s.id}
                              session={s}
                              courseId={courseId}
                            />
                          ))}
                        </ul>
                      )}
                      <AddLessonForm module={m} courseId={courseId} />
                    </div>
                  )}
                </li>
              );
            })}
          </ul>
        </SortableContext>
      </DndContext>
      <AddModuleForm courseId={courseId} nextOrder={modules.length} />
    </div>
  );
}

/** Rename / delete a module, inline in its header row. */
function ModuleRowActions({
  module: m,
  courseId,
  lessonCount,
}: {
  module: ModuleDto;
  courseId: string;
  lessonCount: number;
}): JSX.Element | null {
  const qc = useQueryClient();
  const { isOversight } = useCourseOversight();
  const [renaming, setRenaming] = useState(false);
  const [draft, setDraft] = useState(m.title);
  const [err, setErr] = useState<string | null>(null);

  const refresh = (): void => {
    qc.invalidateQueries({ queryKey: ['course', courseId, 'shell'] });
    qc.invalidateQueries({ queryKey: ['course', courseId, 'sessions'] });
  };
  const renameMut = useMutation({
    mutationFn: () => modulesApi.update(m.id, { title: draft.trim() }),
    onSuccess: () => { setRenaming(false); setErr(null); refresh(); },
    onError: (e) => setErr(e instanceof ApiHttpError ? e.message : 'Rename failed.'),
  });
  const deleteMut = useMutation({
    mutationFn: () => modulesApi.remove(m.id),
    onSuccess: () => { setErr(null); refresh(); },
    onError: (e) => setErr(e instanceof ApiHttpError ? e.message : 'Delete failed.'),
  });

  if (isOversight) return null;
  return (
    <div className="px-5 pb-2 -mt-1 flex items-center gap-2 text-xs">
      {renaming ? (
        <form
          className="flex items-center gap-2 flex-1"
          onSubmit={(e) => { e.preventDefault(); if (draft.trim()) renameMut.mutate(); }}
        >
          <input
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            autoFocus
            className="flex-1 h-9 px-2.5 rounded-lg border border-black/15 focus:outline-none focus:ring-2 focus:ring-brand-navy/20"
          />
          <Button type="submit" size="sm" loading={renameMut.isPending}>Save</Button>
          <Button type="button" size="sm" variant="ghost" onClick={() => setRenaming(false)}>Cancel</Button>
        </form>
      ) : (
        <>
          <button
            type="button"
            onClick={() => { setDraft(m.title); setRenaming(true); }}
            className="text-muted hover:text-brand-navy hover:underline"
          >
            rename module
          </button>
          <button
            type="button"
            disabled={deleteMut.isPending}
            onClick={() => {
              if (window.confirm(`Delete the module "${m.title}" and its ${lessonCount} lesson(s)?`)) {
                deleteMut.mutate();
              }
            }}
            className="text-danger hover:underline disabled:opacity-50"
          >
            delete module
          </button>
        </>
      )}
      {err && <span className="text-danger">{err}</span>}
    </div>
  );
}

/** Add a module to the course. */
function AddModuleForm({ courseId, nextOrder }: { courseId: string; nextOrder: number }): JSX.Element | null {
  const qc = useQueryClient();
  const { isOversight } = useCourseOversight();
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState('');
  const [err, setErr] = useState<string | null>(null);

  const createMut = useMutation({
    mutationFn: () => modulesApi.createOnCourse(courseId, { title: title.trim(), order: nextOrder }),
    onSuccess: () => {
      setTitle(''); setOpen(false); setErr(null);
      qc.invalidateQueries({ queryKey: ['course', courseId, 'shell'] });
    },
    onError: (e) => setErr(e instanceof ApiHttpError ? e.message : 'Could not add the module.'),
  });

  if (isOversight) return null;
  if (!open) {
    return (
      <Button size="sm" variant="secondary" onClick={() => setOpen(true)}>
        + Add module
      </Button>
    );
  }
  return (
    <form
      className="rounded-2xl border border-black/5 bg-white p-4 space-y-3"
      onSubmit={(e) => {
        e.preventDefault();
        setErr(null);
        if (!title.trim()) { setErr('Give the module a title.'); return; }
        createMut.mutate();
      }}
    >
      <Input
        label="Module title"
        placeholder="e.g. Retail Operations and Compliance"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        autoFocus
      />
      {err && <p className="text-danger text-sm">{err}</p>}
      <div className="flex gap-2">
        <Button type="submit" size="sm" loading={createMut.isPending}>Add module</Button>
        <Button type="button" size="sm" variant="ghost" onClick={() => { setOpen(false); setTitle(''); setErr(null); }}>
          Cancel
        </Button>
      </div>
    </form>
  );
}

/**
 * Add a lesson (session) to a module by hand. Only shown to users who can
 * write the course (assigned faculty) — an admin/superadmin in oversight mode
 * sees nothing here (the server also rejects the write). Lessons added this
 * way survive curriculum re-imports.
 */
function AddLessonForm({ module: m, courseId }: { module: ModuleDto; courseId: string }): JSX.Element | null {
  const qc = useQueryClient();
  const { isOversight } = useCourseOversight();
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState('');
  const [minutes, setMinutes] = useState('');
  const [error, setError] = useState<string | null>(null);

  const createMut = useMutation({
    mutationFn: () =>
      sessionsApi.create(courseId, {
        moduleId: m.id,
        title: title.trim(),
        plannedMinutes: minutes.trim() ? Number(minutes) : null,
      }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['course', courseId, 'sessions'] });
      setTitle('');
      setMinutes('');
      setOpen(false);
      setError(null);
    },
    onError: (e) => setError(e instanceof ApiHttpError ? e.message : 'Could not add the lesson.'),
  });

  if (isOversight) return null;

  if (!open) {
    return (
      <div className="px-5 py-3 border-t border-black/5">
        <Button size="sm" variant="secondary" onClick={() => setOpen(true)}>
          + Add lesson
        </Button>
      </div>
    );
  }

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        setError(null);
        if (!title.trim()) {
          setError('Give the lesson a title.');
          return;
        }
        createMut.mutate();
      }}
      className="px-5 py-4 border-t border-black/5 space-y-3 bg-surface-muted/40"
    >
      <div className="grid gap-3 sm:grid-cols-[1fr_150px]">
        <Input
          label="Lesson title"
          placeholder="e.g. Store layout & visual merchandising basics"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          autoFocus
        />
        <Input
          label="Minutes (optional)"
          type="number"
          placeholder="e.g. 90"
          value={minutes}
          onChange={(e) => setMinutes(e.target.value)}
        />
      </div>
      {error && <p className="text-danger text-sm">{error}</p>}
      <div className="flex gap-2">
        <Button type="submit" size="sm" loading={createMut.isPending}>
          Add lesson
        </Button>
        <Button
          type="button"
          size="sm"
          variant="ghost"
          onClick={() => {
            setOpen(false);
            setTitle('');
            setMinutes('');
            setError(null);
          }}
        >
          Cancel
        </Button>
      </div>
    </form>
  );
}

/**
 * PR #16 — module overview panel. Renders the curriculum-import metadata
 * that previously sat invisible on the model: aim/description, learning
 * outcomes, prerequisites, and faculty-private notes. Description and
 * notes are editable inline; outcomes are read-only here (admin-edit
 * lives in the curriculum import / Settings tab).
 *
 * Disabled when the user is in oversight mode (admin/superadmin not on
 * the faculty roster) — mirrors the server gate in
 * `assertFacultyCanWriteCourse`.
 */
function ModuleOverviewPanel({ module: m }: { module: ModuleDto }): JSX.Element {
  const qc = useQueryClient();
  const { isOversight } = useCourseOversight();
  const [aimDraft, setAimDraft] = useState<string>(m.aim ?? '');
  const [notesDraft, setNotesDraft] = useState<string>(m.facultyNotes ?? '');
  const [syllabusDraft, setSyllabusDraft] = useState<string>(m.syllabus ?? '');
  // Re-seed when the prop changes (e.g. after a successful save invalidates
  // the parent query and re-renders this row).
  useEffect(() => {
    setAimDraft(m.aim ?? '');
  }, [m.aim]);
  useEffect(() => {
    setNotesDraft(m.facultyNotes ?? '');
  }, [m.facultyNotes]);
  useEffect(() => {
    setSyllabusDraft(m.syllabus ?? '');
  }, [m.syllabus]);
  const [glossaryDraft, setGlossaryDraft] = useState<GlossaryEntryDto[]>(m.glossary ?? []);
  const [readingDraft, setReadingDraft] = useState<ReadingItemDto[]>(m.readingList ?? []);
  useEffect(() => {
    setGlossaryDraft(m.glossary ?? []);
  }, [m.glossary]);
  useEffect(() => {
    setReadingDraft(m.readingList ?? []);
  }, [m.readingList]);
  const [aimSaved, setAimSaved] = useState(false);
  const [notesSaved, setNotesSaved] = useState(false);
  const [syllabusSaved, setSyllabusSaved] = useState(false);
  const [glossarySaved, setGlossarySaved] = useState(false);
  const [readingSaved, setReadingSaved] = useState(false);

  const updateMut = useMutation({
    mutationFn: (patch: {
      aim?: string;
      facultyNotes?: string;
      syllabus?: string;
      syllabusFile?: { fileId: string } | null;
      glossary?: GlossaryEntryDto[];
      readingList?: ReadingItemDto[];
    }) => modulesApi.update(m.id, patch),
    onSuccess: (_doc, vars) => {
      if (vars.aim !== undefined) {
        setAimSaved(true);
        window.setTimeout(() => setAimSaved(false), 2000);
      }
      if (vars.facultyNotes !== undefined) {
        setNotesSaved(true);
        window.setTimeout(() => setNotesSaved(false), 2000);
      }
      if (vars.syllabus !== undefined) {
        setSyllabusSaved(true);
        window.setTimeout(() => setSyllabusSaved(false), 2000);
      }
      if (vars.glossary !== undefined) {
        setGlossarySaved(true);
        window.setTimeout(() => setGlossarySaved(false), 2000);
      }
      if (vars.readingList !== undefined) {
        setReadingSaved(true);
        window.setTimeout(() => setReadingSaved(false), 2000);
      }
      qc.invalidateQueries({ queryKey: ['course', m.courseId, 'shell'] });
    },
  });

  const aimDirty = aimDraft !== (m.aim ?? '');
  const notesDirty = notesDraft !== (m.facultyNotes ?? '');
  const syllabusDirty = syllabusDraft !== (m.syllabus ?? '');
  const oversightTitle = 'Read-only in oversight mode';

  // Syllabus file upload — separate state from the textarea so we can
  // surface a granular error/loading row without clobbering the rest of
  // the panel.
  const [syllabusFileError, setSyllabusFileError] = useState<string | null>(null);
  const uploadSyllabusFile = useMutation({
    mutationFn: async (file: File) => {
      const { key } = await filesApi.upload(file, 'course-pdfs');
      await modulesApi.update(m.id, { syllabusFile: { fileId: key } });
    },
    onSuccess: () => {
      setSyllabusFileError(null);
      qc.invalidateQueries({ queryKey: ['course', m.courseId, 'shell'] });
    },
    onError: (e) =>
      setSyllabusFileError(e instanceof ApiHttpError ? e.message : 'Upload failed.'),
  });
  const removeSyllabusFile = useMutation({
    mutationFn: () => modulesApi.update(m.id, { syllabusFile: null }),
    onSuccess: () => {
      setSyllabusFileError(null);
      qc.invalidateQueries({ queryKey: ['course', m.courseId, 'shell'] });
    },
    onError: (e) =>
      setSyllabusFileError(e instanceof ApiHttpError ? e.message : 'Remove failed.'),
  });

  async function handleSyllabusFile(file: File): Promise<void> {
    setSyllabusFileError(null);
    if (file.size > 5 * 1024 * 1024) {
      setSyllabusFileError('File must be 5 MB or smaller.');
      return;
    }
    await uploadSyllabusFile.mutateAsync(file);
  }

  function formatBytes(n: number): string {
    if (n < 1024) return `${n} B`;
    if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
    return `${(n / (1024 * 1024)).toFixed(1)} MB`;
  }

  const aimError = updateMut.error instanceof ApiHttpError ? updateMut.error.message : null;

  return (
    <div className="px-5 py-4 bg-surface-muted/40 border-b border-black/5 space-y-4">
      <div>
        <p className="text-xs uppercase tracking-wider text-muted font-bold mb-1.5">
          Module overview
        </p>
        <TextArea
          label="Description"
          rows={4}
          value={aimDraft}
          onChange={(e) => setAimDraft(e.target.value)}
          placeholder="What is this module about? Faculty + students will see this."
          disabled={isOversight}
          maxLength={8000}
        />
        <div className="mt-2 flex items-center gap-2">
          <Button
            size="sm"
            variant="secondary"
            loading={updateMut.isPending && updateMut.variables?.aim !== undefined}
            disabled={!aimDirty || isOversight}
            onClick={() => updateMut.mutate({ aim: aimDraft })}
            title={isOversight ? oversightTitle : undefined}
          >
            Save description
          </Button>
          {aimSaved && <span className="text-xs text-success">Saved.</span>}
        </div>
      </div>
      <div>
        <p className="text-xs uppercase tracking-wider text-muted font-bold mb-1.5">
          Syllabus <span className="font-normal normal-case text-muted">— long-form, visible to students</span>
        </p>
        <TextArea
          rows={6}
          value={syllabusDraft}
          onChange={(e) => setSyllabusDraft(e.target.value)}
          placeholder="Topics, sequencing, deliverables, references — anything a student needs to know to follow the module."
          disabled={isOversight}
          maxLength={16_000}
        />
        <div className="mt-2 flex items-center gap-2">
          <Button
            size="sm"
            variant="secondary"
            loading={updateMut.isPending && updateMut.variables?.syllabus !== undefined}
            disabled={!syllabusDirty || isOversight}
            onClick={() => updateMut.mutate({ syllabus: syllabusDraft })}
            title={isOversight ? oversightTitle : undefined}
          >
            Save syllabus
          </Button>
          {syllabusSaved && <span className="text-xs text-success">Saved.</span>}
        </div>
        {/* Optional uploaded syllabus document — students see a download
            link alongside the long-form text. Drag-and-drop avoids the
            native OS file dialog (which hangs on OneDrive setups). */}
        <div className="mt-3">
          {m.syllabusFile ? (
            <div className="flex flex-wrap items-center gap-3 rounded-xl border border-dashed border-black/10 bg-white/60 p-3">
              <FileLink
                url={`/v1/files/${m.syllabusFile.fileId}`}
                className="text-sm font-medium text-brand-navy hover:underline truncate"
              >
                📄 {m.syllabusFile.filename}
              </FileLink>
              <span className="text-xs text-muted">
                {formatBytes(m.syllabusFile.size)}
              </span>
              <div className="ml-auto flex items-center gap-2">
                <Button
                  size="sm"
                  variant="ghost"
                  className="text-danger hover:bg-red-50"
                  loading={removeSyllabusFile.isPending}
                  disabled={isOversight}
                  onClick={() => removeSyllabusFile.mutate()}
                >
                  Remove
                </Button>
              </div>
            </div>
          ) : (
            <FileDropZone
              onFile={(f) => {
                handleSyllabusFile(f).catch(() => {
                  /* surfaced via uploadSyllabusFile.onError */
                });
              }}
              accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
              maxBytes={5 * 1024 * 1024}
              disabled={isOversight}
              busy={uploadSyllabusFile.isPending}
              busyLabel="Uploading syllabus…"
              label="Drag a syllabus document here"
              hint="PDF or Word (.doc / .docx), 5 MB max. Students see a download link."
            />
          )}
          {m.syllabusFile && !isOversight && (
            <div className="mt-2">
              <FileDropZone
                onFile={(f) => {
                  handleSyllabusFile(f).catch(() => undefined);
                }}
                accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                maxBytes={5 * 1024 * 1024}
                busy={uploadSyllabusFile.isPending}
                busyLabel="Replacing…"
                label="Drag a new file here to replace"
                hint="Replaces the current document."
              />
            </div>
          )}
          {syllabusFileError && (
            <p className="mt-2 text-xs text-danger">{syllabusFileError}</p>
          )}
        </div>
      </div>
      <div>
        <p className="text-xs uppercase tracking-wider text-muted font-bold mb-1.5">
          Glossary <span className="font-normal normal-case text-muted">— module terms, visible to students</span>
        </p>
        <GlossaryEditor
          value={glossaryDraft}
          onChange={setGlossaryDraft}
          disabled={isOversight}
        />
        {!isOversight && (
          <div className="mt-2 flex items-center gap-2">
            <Button
              size="sm"
              variant="secondary"
              loading={updateMut.isPending && updateMut.variables?.glossary !== undefined}
              onClick={() => updateMut.mutate({ glossary: glossaryDraft })}
            >
              Save glossary
            </Button>
            {glossarySaved && <span className="text-xs text-success">Saved.</span>}
          </div>
        )}
      </div>
      <div>
        <p className="text-xs uppercase tracking-wider text-muted font-bold mb-1.5">
          Reading list <span className="font-normal normal-case text-muted">— module readings, visible to students</span>
        </p>
        <ReadingListEditor
          value={readingDraft}
          onChange={setReadingDraft}
          disabled={isOversight}
        />
        {!isOversight && (
          <div className="mt-2 flex items-center gap-2">
            <Button
              size="sm"
              variant="secondary"
              loading={updateMut.isPending && updateMut.variables?.readingList !== undefined}
              onClick={() => updateMut.mutate({ readingList: readingDraft })}
            >
              Save reading list
            </Button>
            {readingSaved && <span className="text-xs text-success">Saved.</span>}
          </div>
        )}
      </div>
      {m.learningOutcomes.length > 0 && (
        <div>
          <p className="text-xs uppercase tracking-wider text-muted font-bold mb-1.5">
            Learning outcomes
          </p>
          <ul className="space-y-1.5">
            {m.learningOutcomes.map((lo) => (
              <li key={lo.mloId} className="flex gap-2 text-sm">
                <Badge tone="info" size="sm">{lo.code || lo.mloId}</Badge>
                <span className="text-ink/85 leading-relaxed max-w-[68ch]">{lo.statement}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
      {m.prerequisites.length > 0 && (
        <div>
          <p className="text-xs uppercase tracking-wider text-muted font-bold mb-1.5">
            Prerequisites
          </p>
          <ul className="list-disc list-inside text-sm text-ink/85 space-y-0.5">
            {m.prerequisites.map((p, i) => (
              <li key={i}>{p}</li>
            ))}
          </ul>
        </div>
      )}
      <div>
        <p className="text-xs uppercase tracking-wider text-muted font-bold mb-1.5">
          Internal notes <span className="font-normal normal-case text-muted">— faculty-only, never shown to students</span>
        </p>
        <TextArea
          rows={3}
          value={notesDraft}
          onChange={(e) => setNotesDraft(e.target.value)}
          placeholder="Pacing, common stumbling blocks, what to emphasize for this cohort…"
          disabled={isOversight}
          maxLength={8000}
        />
        <div className="mt-2 flex items-center gap-2">
          <Button
            size="sm"
            variant="secondary"
            loading={updateMut.isPending && updateMut.variables?.facultyNotes !== undefined}
            disabled={!notesDirty || isOversight}
            onClick={() => updateMut.mutate({ facultyNotes: notesDraft })}
            title={isOversight ? oversightTitle : undefined}
          >
            Save notes
          </Button>
          {notesSaved && <span className="text-xs text-success">Saved.</span>}
        </div>
      </div>
      {aimError && <p className="text-xs text-danger">{aimError}</p>}
    </div>
  );
}

function SortableSessionRow({
  session,
  courseId,
}: {
  session: SessionDto;
  courseId: string;
}): JSX.Element {
  const qc = useQueryClient();
  const { isOversight } = useCourseOversight();
  const [renaming, setRenaming] = useState(false);
  const [draftTitle, setDraftTitle] = useState(session.title);
  const [rowError, setRowError] = useState<string | null>(null);

  const renameMut = useMutation({
    mutationFn: () => sessionsApi.update(session.id, { title: draftTitle.trim() }),
    onSuccess: () => {
      setRenaming(false);
      setRowError(null);
      qc.invalidateQueries({ queryKey: ['course', courseId, 'sessions'] });
    },
    onError: (e) => setRowError(e instanceof ApiHttpError ? e.message : 'Rename failed.'),
  });
  const deleteMut = useMutation({
    mutationFn: () => sessionsApi.remove(session.id),
    onSuccess: () => {
      setRowError(null);
      qc.invalidateQueries({ queryKey: ['course', courseId, 'sessions'] });
    },
    onError: (e) => setRowError(e instanceof ApiHttpError ? e.message : 'Delete failed.'),
  });

  const draggable = !session.isAutoGenerated;
  const sortable = useSortable({ id: session.id, disabled: !draggable });
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = sortable;
  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : 1,
  };

  const statusTone = session.status === 'completed' ? 'success'
    : session.status === 'in_progress' ? 'warning'
    : 'neutral';

  return (
    <li
      ref={setNodeRef}
      style={style}
      className={`flex items-center gap-3 px-5 py-3 hover:bg-surface-muted/50 ${isDragging ? 'shadow-lg' : ''}`}
    >
      <button
        type="button"
        aria-label={draggable ? `Drag ${session.title}` : 'Auto-generated, not draggable'}
        {...(draggable ? attributes : {})}
        {...(draggable ? listeners : {})}
        disabled={!draggable}
        className={`shrink-0 h-7 w-7 rounded-md grid place-items-center text-muted ${
          draggable
            ? 'cursor-grab active:cursor-grabbing hover:bg-black/5'
            : 'cursor-not-allowed opacity-40'
        }`}
        title={draggable ? 'Drag to reorder' : 'Auto-generated — locked'}
      >
        <svg viewBox="0 0 16 16" className="h-4 w-4" aria-hidden>
          <circle cx="6" cy="3" r="1.2" fill="currentColor" />
          <circle cx="10" cy="3" r="1.2" fill="currentColor" />
          <circle cx="6" cy="8" r="1.2" fill="currentColor" />
          <circle cx="10" cy="8" r="1.2" fill="currentColor" />
          <circle cx="6" cy="13" r="1.2" fill="currentColor" />
          <circle cx="10" cy="13" r="1.2" fill="currentColor" />
        </svg>
      </button>
      {renaming ? (
        <form
          className="flex-1 min-w-0 flex items-center gap-2"
          onSubmit={(e) => { e.preventDefault(); if (draftTitle.trim()) renameMut.mutate(); }}
        >
          <input
            value={draftTitle}
            onChange={(e) => setDraftTitle(e.target.value)}
            autoFocus
            className="flex-1 min-w-0 h-9 px-2.5 rounded-lg border border-black/15 focus:outline-none focus:ring-2 focus:ring-brand-navy/20"
          />
          <Button type="submit" size="sm" loading={renameMut.isPending}>Save</Button>
          <Button type="button" size="sm" variant="ghost" onClick={() => setRenaming(false)}>Cancel</Button>
        </form>
      ) : (
      <Link
        to={`/courses/${courseId}/sessions/${session.id}`}
        className="flex-1 min-w-0 flex items-center gap-3"
      >
        <span className="font-mono text-xs text-muted shrink-0">
          {String(session.orderIndex + 1).padStart(2, '0')}
        </span>
        <span className="font-medium text-brand-navy truncate">{session.title}</span>
        {session.isAutoGenerated && (
          <Badge tone="accent" size="sm">Auto-generated</Badge>
        )}
        {session.plannedMinutes && (
          <span className="text-xs text-muted shrink-0">{session.plannedMinutes} min</span>
        )}
      </Link>
      )}
      <Badge tone={statusTone} size="sm">
        {session.status === 'in_progress' ? 'in progress' : session.status}
      </Badge>
      {!isOversight && !session.isAutoGenerated && (
        <span className="shrink-0 flex items-center gap-1">
          <button
            type="button"
            onClick={() => { setDraftTitle(session.title); setRenaming(true); }}
            className="text-xs text-muted hover:text-brand-navy hover:underline"
          >
            rename
          </button>
          <button
            type="button"
            disabled={deleteMut.isPending}
            onClick={() => {
              if (window.confirm(`Delete the lesson "${session.title}"? Its materials go with it.`)) {
                deleteMut.mutate();
              }
            }}
            className="text-xs text-danger hover:underline disabled:opacity-50"
          >
            delete
          </button>
        </span>
      )}
      {rowError && <span className="text-xs text-danger">{rowError}</span>}
    </li>
  );
}
